import { Product } from '@/types'

export const products: Product[] = [
  {
    id: 'p1',
    name: 'CloudStep Running Shoes',
    price: 3499,
    originalPrice: 4999,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
    category: 'Footwear',
    rating: 4.6,
    reviews: 2341,
    badge: '30% OFF',
    description: 'Lightweight daily trainer with responsive cushioning. Perfect for 5K to marathon distances.',
    sizes: ['6', '7', '7.5', '8', '8.5', '9', '10', '11'],
    deliveryDays: 2,
    inStock: true,
  },
  {
    id: 'p2',
    name: 'Urban Comfort Backpack',
    price: 1899,
    originalPrice: 2499,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80',
    category: 'Bags',
    rating: 4.8,
    reviews: 891,
    badge: 'Best Seller',
    description: '25L capacity with laptop compartment. Water resistant with ergonomic straps.',
    deliveryDays: 3,
    inStock: true,
  },
  {
    id: 'p3',
    name: 'Premium Wireless Earbuds',
    price: 2299,
    originalPrice: 3499,
    image: 'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=600&q=80',
    category: 'Electronics',
    rating: 4.5,
    reviews: 3102,
    badge: 'New',
    description: 'Active noise cancellation, 30hr battery life, IPX4 water resistance.',
    deliveryDays: 1,
    inStock: true,
  },
  {
    id: 'p4',
    name: 'Merino Wool Crew Neck',
    price: 1599,
    originalPrice: 2199,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80',
    category: 'Clothing',
    rating: 4.7,
    reviews: 567,
    description: '100% Merino wool, temperature regulating, anti-odor, machine washable.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    deliveryDays: 3,
    inStock: true,
  },
  {
    id: 'p5',
    name: 'Smart Water Bottle',
    price: 899,
    originalPrice: 1299,
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80',
    category: 'Lifestyle',
    rating: 4.4,
    reviews: 1204,
    badge: 'Trending',
    description: 'Tracks hydration, glows to remind you to drink, 600ml capacity.',
    deliveryDays: 2,
    inStock: true,
  },
  {
    id: 'p6',
    name: 'Yoga & Training Mat',
    price: 1299,
    originalPrice: 1799,
    image: 'https://images.unsplash.com/photo-1601925228209-de56aa9e2e79?w=600&q=80',
    category: 'Fitness',
    rating: 4.6,
    reviews: 788,
    description: '6mm thick, non-slip surface, alignment lines, carrying strap included.',
    deliveryDays: 2,
    inStock: true,
  },
]

export const storeInfo = {
  name: 'Veloce',
  tagline: 'Gear for the way you move',
  trustBadges: [
    '100,000+ happy customers',
    'Free returns within 30 days',
    'Secure payments',
    '2-day delivery available',
  ],
  paymentMethods: ['Visa', 'Mastercard', 'UPI', 'Net Banking', 'EMI'],
}
